### ISSUE TITLE
Syntax highlight code segments in exercise text

### ISSUE THREAD

**Issue by simon04** [osmlab/learnoverpass#10]
When reading the exercise text it is difficult to differentiate normal text from code segments. Adding a syntax highlighting (ideally, the same from the code box) would ease the reading …

![code](https://cloud.githubusercontent.com/assets/782446/9332384/a30754d8-45c4-11e5-87e9-bb36b1a6bd5d.png)

**Comment by Secretmapper** [comment]
Unfortunately, the syntax highlighting that's being used right now in the docs is a CodeMirror Instance. I've been looking for a more elegant solution to this (as spawning a code mirror instance for every code snippet might bog the page down). 

In the meantime 7709cb1aed1850a07e63628cf096d940d875adc8 recolours the code, which should make it a bit easier to read. Since the code snippets on the exercise page shouldn't really be long, I think this would suffice.
