### ISSUE TITLE
error on opening http://osmlab.github.io/learnoverpass/en/exercises/intro/1/

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/learnoverpass#19]
I got

```
An error occured during the execution of the overpass query!
This is what overpass API returned:



<p><strong style="color:#FF0000">Error</strong>: line 1: parse error: An empty query is not allowed </p>
```

**Comment by abitrolly** [comment]
@bhousel Hi Bryan. Do you know who can fix the tutorial? In https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL I couldn't find a minimal example.

**Comment by bhousel** [comment]
> Hi Bryan. Do you know who can fix the tutorial?

Sorry I don't know!  It looks like this is no longer maintained.

**Comment by abitrolly** [comment]
Nobody from @osmlab who know how it works?

**Comment by irnc** [comment]
@abitrolly This issue is fixed in pull request #22.

/cc @bhousel @Secretmapper @tyrasd I would be happy to become maintainer of LearnOverpass. Please see pull requests #21 and #22 which restore main functionality.

After restoration work I have the following plan:
- fix non-critical errors and issues
- do a code cleanup
- port to upstream i18n support in Hugo
- ask community for exercise translations

**Comment by bhousel** [comment]
> I would be happy to become maintainer of LearnOverpass. Please see pull requests #21 and #22 which restore main functionality.

Thanks @irnc , I've invited you to be the maintainer for the project!

**Comment by irnc** [comment]
This issue was fixed by 34e352d.

Fix was deployed to https://osmlab.github.io/learnoverpass/en/, so feel free to use it, but keep in mind that we have another known issue #24 which sometimes causes _Run Query_ button to be disabled. Until it is fixed, please use LearnOverpass in non-incognito mode and refresh page when _Run Query_ button is disabled on initial page load.

**Comment by abitrolly** [comment]
I hit #24 too and had to refresh the page.

The initial query is invalid and gives the error.

![image](https://user-images.githubusercontent.com/8781107/65306708-c0eb5d00-db8e-11e9-8882-9ceb95a0c335.png)

What is the valid minimal query to insert on the first page?

**Comment by irnc** [comment]
First exercise is solved by the following query:
```
node(48.5657094, 13.4490548, 48.5662416, 13.4501676);
out;
```

If you already tried it, please try again ;) as a fix for #25 was just deployed. That issue prevented almost all exercises to pass.

**Comment by abitrolly** [comment]
There is still the error on the map when the page is loaded. Starting tutorial with the error is not a good user experience, because you can never tell if the error is intentional, or it is a broken tutorial. I suspected a broken tutorial after overpass syntax change, that's why I asked for a minimal valid query.

Another problem is that syntax like `node(48.5657, 13.44, 48.5662, 13.45);` is perfectly valid, and the map renders successfully, but the error message is misleading:

![image](https://user-images.githubusercontent.com/8781107/65520568-75b7ae00-def0-11e9-8279-4e0d768917f1.png)

If the syntax is right, I would expect it to say "The syntax is correct. Try to enter exact GPS coordinates to pass to the next level.".

**Comment by irnc** [comment]
@Secretmapper Thanks! Hope you are doing well. I will work on the roadmap soon to make project better prepared for new contributors. I would be glad to receive feedback on it once it is drafted.

@abitrolly Thanks for feedback, these are all good points! Could you please extract them into separate issues, so they could be worked out independently?

**Comment by abitrolly** [comment]
@irnc moved the aforementioned points into #32 and #33.
