### ISSUE TITLE
Example for Filter by inputset needs review

### ISSUE THREAD

**Issue by mmd-osm** [osmlab/learnoverpass#6]
The following two queries on Filter by inputset probably need to be revised: http://osmlab.github.io/learnoverpass/en/docs/filters/input-set/

Right now, it would print the same info (relation + members) twice, once with full details and once just with reduced details. I think that's probably not intended?

```
(relation[name="Cividale del Friuli"];>;);
out body;
out skel qt;

(relation[name="Julijske Alpe"];>;);
out body;
out skel qt;
```

**Comment by Secretmapper** [comment]
You're right! This query is going to benefit from a revisit and more samples:

There should be a simpler example for this (one that's just a filters the input set).

The current example specifically shows intersection (`node.Alpe_nodes.Cividale_nodes;`) The reason for printing the relation again is so that the user sees how the nodes printed are only those inside both areas - but the size difference between the two makes it hard to see (sort of going for a venn diagram kind of effect here)
