### ISSUE TITLE
Example for out modifiers

### ISSUE THREAD

**Issue by mmd-osm** [osmlab/learnoverpass#8]
`out` modifiers are quite useful, but somehow get a bit lost on the respective [page](http://osmlab.github.io/learnoverpass/en/docs/actions/print/)

How about adding a query, which demonstrates all of them at once:

```
[date:"2014-12-30T00:00:00Z"];
way(34345085);
out geom; 
out center;        // not a centroid, e.g. not guaranteed to lie inside polygon
out bb;            // bounding box
```

![bb](https://cloud.githubusercontent.com/assets/5842757/8395745/4f8a3456-1d83-11e5-820c-1bf3a75b3979.png)

**Comment by Secretmapper** [comment]
Awesome sample and I think this could work!

Alternatively, I've been meaning to address this in another way. I'm currently reworking the embedded map of Overpass Turbo to allow 'caching' of data, so that it'd be super easy and fast to 'change queries' and show the different modifiers quickly with a click of the button (almost like a click and compare feature)

I'll try how that feels, but I don't see any disadvantage of using this as an 'uber' example that shows all of the modifiers at once :)
